version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
  sender:
    build: ./sender
    depends_on:
      - server
    volumes:
      - ./sender:/sender
